<a href="https://colab.research.google.com/github/Hitaishianand/data-mining-and-analytics/blob/main/us_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import pandas as pd

In [136]:
import numpy as np

In [137]:
import seaborn as sns

In [138]:
df = pd.read_csv("/content/drive/MyDrive/data mining/US_Heart_Patients.csv")

In [139]:
df

,Gender,age,education,currentSmoker,cigsPerDay,BP Meds,prevalentStroke,prevalentHyp,diabetes,tot cholesterol,Systolic BP,Diastolic BP,BMI,heartRate,glucose,Heart-Att
0,Male,39.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,Female,46.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,Male,48.0,1.0,1.0,20.0,0.0,0.0,0.0,0.0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,Female,61.0,3.0,1.0,30.0,0.0,0.0,1.0,0.0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,Female,46.0,3.0,1.0,23.0,0.0,0.0,0.0,0.0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,Female,48.0,2.0,1.0,20.0,NaN,0.0,0.0,0.0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,Female,44.0,1.0,1.0,15.0,0.0,0.0,0.0,0.0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,Female,52.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,Male,40.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,Female,39.0,3.0,1.0,30.0,0.0,0.0,0.0,0.0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [140]:
df.tail(5)

,Gender,age,education,currentSmoker,cigsPerDay,BP Meds,prevalentStroke,prevalentHyp,diabetes,tot cholesterol,Systolic BP,Diastolic BP,BMI,heartRate,glucose,Heart-Att
4235,Female,48.0,2.0,1.0,20.0,NaN,0.0,0.0,0.0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,Female,44.0,1.0,1.0,15.0,0.0,0.0,0.0,0.0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,Female,52.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,Male,40.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,Female,39.0,3.0,1.0,30.0,0.0,0.0,0.0,0.0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [141]:
df.head(5)

,Gender,age,education,currentSmoker,cigsPerDay,BP Meds,prevalentStroke,prevalentHyp,diabetes,tot cholesterol,Systolic BP,Diastolic BP,BMI,heartRate,glucose,Heart-Att
0,Male,39.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,Female,46.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,Male,48.0,1.0,1.0,20.0,0.0,0.0,0.0,0.0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,Female,61.0,3.0,1.0,30.0,0.0,0.0,1.0,0.0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,Female,46.0,3.0,1.0,23.0,0.0,0.0,0.0,0.0,285.0,130.0,84.0,23.10,85.0,85.0,0

EDA ( Exploratory Data Analysis )

In [142]:
df.head()

,Gender,age,education,currentSmoker,cigsPerDay,BP Meds,prevalentStroke,prevalentHyp,diabetes,tot cholesterol,Systolic BP,Diastolic BP,BMI,heartRate,glucose,Heart-Att
0,Male,39.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,Female,46.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,Male,48.0,1.0,1.0,20.0,0.0,0.0,0.0,0.0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,Female,61.0,3.0,1.0,30.0,0.0,0.0,1.0,0.0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,Female,46.0,3.0,1.0,23.0,0.0,0.0,0.0,0.0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [143]:
df.shape

(4240, 16)

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4232 non-null   object
 1   age              4238 non-null   float64
 2   education        4130 non-null   float64
 3   currentSmoker    4237 non-null   float64
 4   cigsPerDay       4209 non-null   float64
 5   BP Meds          4180 non-null   float64
 6   prevalentStroke  4231 non-null   float64
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4238 non-null   float64
 9   tot cholesterol  4180 non-null   float64
 10  Systolic BP      4236 non-null   float64
 11  Diastolic BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(14), int64(1), object(1)
memory usage: 530.1+ KB

In [145]:
df["Gender"].value_counts()

Gender
Female    2414
Male      1818
Name: count, dtype: int64

In [146]:
df["education"].value_counts()

education
1.0    1717
2.0    1252
3.0     688
4.0     473
Name: count, dtype: int64

In [147]:
df["currentSmoker"].value_counts()

currentSmoker
0.0    2143
1.0    2094
Name: count, dtype: int64

In [148]:
df["BP Meds"].value_counts()

BP Meds
0.0    4056
1.0     124
Name: count, dtype: int64

In [149]:
df["Heart-Att"].value_counts()

Heart-Att
0    3596
1     644
Name: count, dtype: int64

In [150]:
df["Heart-Att"].value_counts(normalize=True)

Heart-Att
0    0.848113
1    0.151887
Name: proportion, dtype: float64

Change Data Type of Float (that are actually categorical variables)

In [151]:
cat=["education","currentSmoker","BP Meds","prevalentStroke","diabetes"]

In [152]:
for i in cat:
  df[i]=df[i].astype("object")

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4232 non-null   object
 1   age              4238 non-null   float64
 2   education        4130 non-null   object
 3   currentSmoker    4237 non-null   object
 4   cigsPerDay       4209 non-null   float64
 5   BP Meds          4180 non-null   object
 6   prevalentStroke  4231 non-null   object
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4238 non-null   object
 9   tot cholesterol  4180 non-null   float64
 10  Systolic BP      4236 non-null   float64
 11  Diastolic BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB

In [154]:
cat = []
num = []
for i in df.columns:
  if df[i].dtype == "object":
    cat.append(i)
  else:
    num.append(i)

print(cat)
print(num)

['Gender', 'education', 'currentSmoker', 'BP Meds', 'prevalentStroke', 'diabetes']
['age', 'cigsPerDay', 'prevalentHyp', 'tot cholesterol', 'Systolic BP', 'Diastolic BP', 'BMI', 'heartRate', 'glucose', 'Heart-Att']

Stastistical Description of Data

In [155]:
df[num].describe().T

,count,mean,std,min,25%,50%,75%,max
age,4238.0,49.579283,8.572875,32.00,42.00,49.000,56.00,70.0
cigsPerDay,4209.0,9.001901,11.920742,0.00,0.00,0.000,20.00,70.0
prevalentHyp,4238.0,0.310524,0.462763,0.00,0.00,0.000,1.00,1.0
tot cholesterol,4180.0,236.677273,44.616098,107.00,206.00,234.000,263.00,696.0
Systolic BP,4236.0,132.362370,22.039244,83.50,117.00,128.000,144.00,295.0
Diastolic BP,4235.0,82.901889,11.914467,48.00,75.00,82.000,90.00,142.5
BMI,4216.0,25.798916,4.075256,15.54,23.07,25.395,28.04,56.8
heartRate,4236.0,75.867800,11.999488,44.00,68.00,75.000,83.00,143.0
glucose,3849.0,81.951936,23.958428,40.00,71.00,78.000,87.00,394.0
Heart-Att,4240.0,0.151887,0.358953,0.00,0.00,0.000,0.00,1.0

Rename columns with spaces in between their names

In [156]:
df.rename(columns={"tot cholesterol":"tot_cholesterol","BP Meds": "BP_Meds","Systolic BP":"Systolic_BP","Diastolic BP":"Diastolic_BP"},inplace=True)

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4232 non-null   object
 1   age              4238 non-null   float64
 2   education        4130 non-null   object
 3   currentSmoker    4237 non-null   object
 4   cigsPerDay       4209 non-null   float64
 5   BP_Meds          4180 non-null   object
 6   prevalentStroke  4231 non-null   object
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4238 non-null   object
 9   tot_cholesterol  4180 non-null   float64
 10  Systolic_BP      4236 non-null   float64
 11  Diastolic_BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB

IMPUTATION OF MISSING VALUES

In [158]:
df.Gender=df.Gender.fillna("Female")

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4240 non-null   object
 1   age              4238 non-null   float64
 2   education        4130 non-null   object
 3   currentSmoker    4237 non-null   object
 4   cigsPerDay       4209 non-null   float64
 5   BP_Meds          4180 non-null   object
 6   prevalentStroke  4231 non-null   object
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4238 non-null   object
 9   tot_cholesterol  4180 non-null   float64
 10  Systolic_BP      4236 non-null   float64
 11  Diastolic_BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB

In [160]:
for column in ['education','BP_Meds','prevalentStroke','diabetes']:
  mode_val=df[column].mode()[0]
  df[column]=df[column].fillna(mode_val).astype("object")

/tmp/ipykernel_3729/2200382106.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column]=df[column].fillna(mode_val).astype("object")
/tmp/ipykernel_3729/2200382106.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column]=df[column].fillna(mode_val).astype("object")
/tmp/ipykernel_3729/2200382106.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column]=df[column].fillna(mode_val).astype("object")
/tmp/ipykernel_3729/2200382106.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column]=df[column].fillna(mode_val).astype("object")

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4240 non-null   object
 1   age              4238 non-null   float64
 2   education        4240 non-null   object
 3   currentSmoker    4237 non-null   object
 4   cigsPerDay       4209 non-null   float64
 5   BP_Meds          4240 non-null   object
 6   prevalentStroke  4240 non-null   object
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4240 non-null   object
 9   tot_cholesterol  4180 non-null   float64
 10  Systolic_BP      4236 non-null   float64
 11  Diastolic_BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4240 non-null   object
 1   age              4238 non-null   float64
 2   education        4240 non-null   object
 3   currentSmoker    4237 non-null   object
 4   cigsPerDay       4209 non-null   float64
 5   BP_Meds          4240 non-null   object
 6   prevalentStroke  4240 non-null   object
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4240 non-null   object
 9   tot_cholesterol  4180 non-null   float64
 10  Systolic_BP      4236 non-null   float64
 11  Diastolic_BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB

In [163]:
for column in ['age','cigsPerDay','tot_cholesterol','BMI','heartRate','glucose']:
  df[column]=df[column].fillna(df[column].median())

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4240 non-null   object
 1   age              4240 non-null   float64
 2   education        4240 non-null   object
 3   currentSmoker    4237 non-null   object
 4   cigsPerDay       4240 non-null   float64
 5   BP_Meds          4240 non-null   object
 6   prevalentStroke  4240 non-null   object
 7   prevalentHyp     4238 non-null   float64
 8   diabetes         4240 non-null   object
 9   tot_cholesterol  4240 non-null   float64
 10  Systolic_BP      4236 non-null   float64
 11  Diastolic_BP     4235 non-null   float64
 12  BMI              4240 non-null   float64
 13  heartRate        4240 non-null   float64
 14  glucose          4240 non-null   float64
 15  Heart-Att        4240 non-null   int64
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB

In [165]:
df.isnull().sum()

Gender             0
age                0
education          0
currentSmoker      3
cigsPerDay         0
BP_Meds            0
prevalentStroke    0
prevalentHyp       2
diabetes           0
tot_cholesterol    0
Systolic_BP        4
Diastolic_BP       5
BMI                0
heartRate          0
glucose            0
Heart-Att          0
dtype: int64